/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSLock, NSMenu;

@interface DropboxContextMenuState : NSObject
{
    NSMenu *theContextMenu;
    long long theInsertionIndex;
    NSLock *theLock;
}

- (id)init;
- (void)insertIntoContextMenu:(id)arg1 atIndex:(long long)arg2;
- (void)pushFinderContext:(id)arg1;

@end

