/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSToolbar.h"

@interface DropboxToolbar : NSToolbar
{
}

- (void)_notifyView_MovedFromIndex:(long long)arg1 toIndex:(long long)arg2;
- (id)_newItemFromItemIdentifier:(id)arg1 propertyListRepresentation:(id)arg2 requireImmediateLoad:(BOOL)arg3 willBeInsertedIntoToolbar:(BOOL)arg4;
- (void)setSizeMode:(unsigned long long)arg1;

@end

