/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSButton.h"

@class DropboxMenu, NSImage;

@interface DropboxLargeToolbarButton : NSButton
{
    DropboxMenu *theMenu;
    NSImage *toolbar_large;
}

- (id)initWithMenu:(id)arg1 frameSize:(struct CGRect)arg2;
- (void)mouseDown:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)dealloc;

@end

